updated ceph nfs

diff --git a/kubernetes/manifests/storage/rook-ceph-nfs.yaml b/kubernetes/manifests/storage/rook-ceph-nfs.yaml
--- a/kubernetes/manifests/storage/rook-ceph-nfs.yaml
+++ b/kubernetes/manifests/storage/rook-ceph-nfs.yaml
@@ -60,16 +60,31 @@ spec:
               \ \"$CLUSTER\" -i /tmp/export_final.json\n\nrados -p .nfs --namespace\
               \ $NFSNS get \"conf-nfs.$CLUSTER\"     /tmp/conf-nfs               \
               \ || true\nrados -p .nfs --namespace $NFSNS get \"export-$EXPORT_ID\"\
-              \     /tmp/export-$$EXPORT_ID     || true\n\necho \"---------------------------\
-              \ CONTENTS -----------------------------\"\ncat /tmp/conf-nfs      \
-              \          || echo \"(conf-nfs not found)\"\necho \"------------------------------------------------------------------\"\
+              \     /tmp/export-$$EXPORT_ID     || true\n\necho \"Fetching user_id\
+              \ from export-$EXPORT_ID\"\nUSER_ID=$(grep -oP 'user_id\\s*=\\s*\"\\\
+              K[^\"]+' /tmp/export.json)\necho \"User ID: $USER_ID\"\n\nBASE_EXPORT_CONF='EXPORT\
+              \ {\n  Export_Id = 0;\n  Path = \"/\";\n  Pseudo = \"/\";\n  Access_Type\
+              \ = RW;\n  Squash = All_Squash;\n  SecType = \"sys\";\n  Security_Label\
+              \ = false;\n  FSAL {\n    Name = CEPH;\n    User_Id = \"__USER_ID__\"\
+              ;\n    Filesystem = \"ceph-filesystem\";\n  }\n}\n'\nBASE_EXPORT_CONF=\"\
+              $${BASE_EXPORT_CONF/__USER_ID__/$USER_ID}\"\nprintf '%s\\n' \"$BASE_EXPORT_CONF\"\
+              \ > /tmp/export_base.conf\n\ncat /tmp/export_base.conf\n\necho \"Uploading\
+              \ updated configs to RADOS...\"\n\nrados -p .nfs --namespace $NFSNS\
+              \ put \"export-0\"     /tmp/export_base.conf\n\necho \"%url    \\\"\
+              rados://.nfs/$CLUSTER/export-0\\\"\" >> /tmp/conf-nfs\n\nrados -p .nfs\
+              \ --namespace $NFSNS put \"conf-nfs.$CLUSTER\"     /tmp/conf-nfs\n\n\
+              echo \"--------------------------- CONTENTS -----------------------------\"\
+              \ncat /tmp/conf-nfs                || echo \"(conf-nfs not found)\"\n\
+              echo \"------------------------------------------------------------------\"\
               \ncat \"/tmp/export-$EXPORT_ID\"     || echo \"(export-$CLUSTER not\
-              \ found)\"\n\necho \"Restarting NFS Ganesha grace...\"\nfor SUFFIX in\
-              \ a b; do\n  ganesha-rados-grace --pool .nfs --ns \"$NFSNS\" add \"\
-              $${CLUSTER}.$${SUFFIX}\"   || true\n  ganesha-rados-grace --pool .nfs\
-              \ --ns \"$NFSNS\" start \"$${CLUSTER}.$${SUFFIX}\" || true\ndone\n\n\
-              echo \"Removing orchestrator backend...\"\nceph -c \"$CEPH_CONFIG\"\
-              \ orch set backend \"\" || true\n\necho \"DONE.\"\n"
+              \ found)\"\necho \"------------------------------------------------------------------\"\
+              \ncat /tmp/export_base.conf        || echo \"(export_base.conf not found)\"\
+              \n\necho \"Restarting NFS Ganesha grace...\"\nfor SUFFIX in a b; do\n\
+              \  ganesha-rados-grace --pool .nfs --ns \"$NFSNS\" add \"$${CLUSTER}.$${SUFFIX}\"\
+              \   || true\n  ganesha-rados-grace --pool .nfs --ns \"$NFSNS\" start\
+              \ \"$${CLUSTER}.$${SUFFIX}\" || true\ndone\n\necho \"Removing orchestrator\
+              \ backend...\"\nceph -c \"$CEPH_CONFIG\" orch set backend \"\" || true\n\
+              \necho \"DONE.\"\n"
           image: quay.io/ceph/ceph:v19
           name: apply
           volumeMounts:
